### ISSUE TITLE
New entity error

### ISSUE THREAD

**Issue by willycornelissen** [raulduran/backendl5#1]
When I add a new entity, i got the following error:

Undefined index: visible (View: <project-dir>/resources/views/layout/partials/sidebar/menu.blade.php) (View: <project-dir>/resources/views/layout/partials/sidebar/menu.blade.php) 

Where can I set the property visible from $menu used on blade's partial to compose the sidebar?

**Comment by raulduran** [comment]
I uploaded the updated documentation. To add one menu option must create the array with visible property, for example:

'articles' => [
     'visible' => true,
     'icon' => 'fa-file-o',
     'edit' => true,
     'name' => trans ('messages.articles.index')
]

**Comment by willycornelissen** [comment]
Thank you Raul. It is working now.

Congratulations for the good job!

**Comment by willycornelissen** [comment]
Do I have to close this issue by myself or will you do this?

**Comment by willycornelissen** [comment]
Thank you Raul. It is working now.

Congratulations for the good job!
