### ISSUE TITLE
Repository should be compatible

### ISSUE THREAD

**Issue by willycornelissen** [raulduran/backendl5#2]
Hello Raul!

When I add a new entity using artisan commands, I have the following error on admin index method:

ErrorException in EscolaRepository.php line 6: Declaration of App\Repositories\EscolaRepository::search() should be compatible with App\Repositories\Repository::search(Illuminate\Http\Request $request, $paginate = true)

The model is named Escola.
Do you know what's happening?

**Comment by raulduran** [comment]
Replace in EscolaRepository.php

function search(Request $request)

for this

function search(Request $request, $paginate=true)

**Comment by willycornelissen** [comment]
Done.

Thank you.
