### ISSUE TITLE
Forms and Validation

### ISSUE THREAD

**Issue by willycornelissen** [raulduran/backendl5#3]
Raul,

I updated the form with extra fields from the new entity, but when I call the update method from admin controller, only the name attribute can be updated. Do I need to change the mehod 'rules' from the new Request object created?

Some properties from the model don't have any validation, and can be even null, how can I declare them on the return array from 'rules' method?

**Comment by raulduran** [comment]
For example in rules method put:

if (($this->method=='POST')
{
   //return rules for new entity
}
else
{
 //return rules for update entity
}

View too app/Http/Requests/UserRequest.php

**Comment by willycornelissen** [comment]
Raul, I found the error.
The problem was with fillabe fields from the model. I put the filelds on the proper array and the problem was solved. 

I was looking for the error message and I could not find any clue, even in storage/log.
This error is saved somewhere?

**Comment by raulduran** [comment]
If errors are saved on storage/logs, you have the permissions right?

**Comment by willycornelissen** [comment]
Yes, I have. I did not receive any error message from CSRF guard from Laravel. I will look with more attention.
