### ISSUE TITLE
Drop-Down in a Form

### ISSUE THREAD

**Issue by willycornelissen** [raulduran/backendl5#4]
Raul,

I was looking for some help to design a Form with drop-down lists to deal with OnetoMany relationships between models. I saw that you use https://github.com/kristijanhusak/laravel-form-builder
to build the forms. I tried the 'select' option with the model as a parameter, but it did not work.

Do you know how can I do a drop-down list in a Form using another model as options?

**Comment by raulduran** [comment]
In your Controller 

```
public function create(FormBuilder $formBuilder, User $user)
{
    $form = $formBuilder->create('App\Forms\ArticleForm', [
        'method' => 'POST',
        'url' => route('admin.article.store'),
        'data' => [
            'users' => $user->getList()
        ]
    ]);

    return view('layout.partials.form', compact('form'));
}
```

In your Form add  field select ...

```
    $this
        ->add('user_id', 'select', [
            'choices' => $this->getData('users'),
            'label' => trans('messages.users')
        ])
```

**Comment by willycornelissen** [comment]
Raul,

It's not working. In the Form field select, the value being passed to choices is returning null:

```
           dd($this->getData('users')); // returning null
    $this
                   ->add('escola_id', 'select', [
                     'choices' => $this->getData('users'),
                     'label' => trans('messages.users')
                ])
```

**Comment by willycornelissen** [comment]
Raul,

I could make the selectbox using User::lists in the form Class, and passing the data to the field.
Thank you.
